# Generated by Django 5.2.10 on 2026-01-25 04:13

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Athlete",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("full_name", models.CharField(max_length=100)),
                ("father_name", models.CharField(blank=True, max_length=100)),
                (
                    "photo",
                    models.ImageField(blank=True, null=True, upload_to="athletes/"),
                ),
                ("registration_date", models.DateField(auto_now_add=True)),
                ("fee_start_date", models.DateField(auto_now_add=True)),
                ("fee_deadline_date", models.DateField()),
                (
                    "gym_type",
                    models.CharField(
                        choices=[
                            ("fitness", "Fitness"),
                            ("bodybuilding", "Bodybuilding"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "gym_time",
                    models.CharField(
                        choices=[
                            ("morning", "Morning"),
                            ("afternoon", "Afternoon"),
                            ("night", "Night"),
                        ],
                        max_length=20,
                    ),
                ),
                (
                    "discount",
                    models.DecimalField(decimal_places=2, default=0, max_digits=10),
                ),
                ("final_fee", models.DecimalField(decimal_places=2, max_digits=10)),
                ("contact_number", models.CharField(blank=True, max_length=15)),
                ("notes", models.TextField(blank=True)),
            ],
        ),
        migrations.CreateModel(
            name="Shelf",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("shelf_number", models.CharField(max_length=10, unique=True)),
                (
                    "status",
                    models.CharField(
                        choices=[("available", "Available"), ("assigned", "Assigned")],
                        default="available",
                        max_length=20,
                    ),
                ),
                (
                    "assigned_athlete",
                    models.OneToOneField(
                        blank=True,
                        null=True,
                        on_delete=django.db.models.deletion.SET_NULL,
                        related_name="assigned_shelf",
                        to="gym.athlete",
                    ),
                ),
            ],
        ),
        migrations.AddField(
            model_name="athlete",
            name="shelf",
            field=models.OneToOneField(
                blank=True,
                null=True,
                on_delete=django.db.models.deletion.SET_NULL,
                to="gym.shelf",
            ),
        ),
    ]
