# Generated by Django 5.2.1 on 2026-02-07 04:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0002_athlete_is_active_payment"),
    ]

    operations = [
        migrations.AddField(
            model_name="shelf",
            name="locker_duration_months",
            field=models.IntegerField(
                blank=True,
                choices=[
                    (1, "1 Month"),
                    (3, "3 Months"),
                    (6, "6 Months"),
                    (12, "12 Months"),
                ],
                null=True,
            ),
        ),
        migrations.AddField(
            model_name="shelf",
            name="locker_end_date",
            field=models.DateField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name="shelf",
            name="locker_price",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="shelf",
            name="locker_start_date",
            field=models.DateField(blank=True, null=True),
        ),
    ]
