# Generated by Django 5.2.1 on 2026-02-07 05:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0003_shelf_locker_duration_months_shelf_locker_end_date_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="shelf",
            name="locker_price",
            field=models.DecimalField(
                blank=True, decimal_places=2, default=None, max_digits=10, null=True
            ),
        ),
    ]
