# Generated by Django 5.2.1 on 2026-02-07 05:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0004_alter_shelf_locker_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="athlete",
            name="registration_date",
            field=models.DateTimeField(auto_now_add=True),
        ),
    ]
