# Generated by Django 5.2.1 on 2026-02-09 04:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0005_alter_athlete_registration_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="athlete",
            name="debt",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Outstanding debt amount",
                max_digits=10,
            ),
        ),
    ]
