# Generated by Django 5.2.1

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0006_athlete_debt"),
    ]

    operations = [
        migrations.AlterField(
            model_name="athlete",
            name="debt",
            field=models.DecimalField(
                decimal_places=2,
                default=0,
                help_text="Outstanding debt amount",
                max_digits=10,
            ),
        ),
    ]
