# Generated by Django 5.2.10 on 2026-06-01 08:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("gym", "0008_add_performance_indexes"),
    ]

    operations = [
        migrations.RemoveIndex(
            model_name="athlete",
            name="gym_athlete_full_name_idx",
        ),
        migrations.RemoveIndex(
            model_name="athlete",
            name="gym_athlete_father_name_idx",
        ),
        migrations.RemoveIndex(
            model_name="athlete",
            name="gym_athlete_contact_idx",
        ),
        migrations.RemoveIndex(
            model_name="athlete",
            name="gym_athlete_is_active_idx",
        ),
        migrations.RemoveIndex(
            model_name="athlete",
            name="gym_athlete_gym_type_idx",
        ),
        migrations.RemoveIndex(
            model_name="athlete",
            name="gym_athlete_gym_time_idx",
        ),
        migrations.RemoveIndex(
            model_name="athlete",
            name="gym_athlete_fee_deadline_idx",
        ),
        migrations.RemoveIndex(
            model_name="athlete",
            name="gym_athlete_reg_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="athlete",
            name="gym_athlete_active_type_idx",
        ),
        migrations.RemoveIndex(
            model_name="athlete",
            name="gym_athlete_active_deadline_idx",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="gym_payment_athlete_idx",
        ),
        migrations.RemoveIndex(
            model_name="payment",
            name="gym_payment_date_idx",
        ),
        migrations.RemoveIndex(
            model_name="shelf",
            name="gym_shelf_status_idx",
        ),
    ]
